= Overview

[cloud-intro]

== (03/21) Module: Cloud Introduction (theory-block I)

=== Intro questions:

* Which technologies or what do you have in mind in general if you think about "distributed systems"?
* the "WHY" - Why would people use and implement a distributed systems architecture?

=== Content

* What is Cloud Computing? Encounters in everyday life and history
* Characteristic, advantages & challenges
* Terminology - public, private, hybrid, dedicated
* Abstraction layers - IaaS, PaaS, FaaS, SaaS
* Overview - Hypervisors, virtual machines, containers and orchestration
* Overview - Global cloud service providers (CSPs), technologies and corresponding offerings

=== Objectives and exercises
_The student is able to describe cloud computing in own words and list examples for offerings, topologies and technologies. Includes ability to differentiate between different abstraction layers and knowledge how those layers and according technologies interact with each other. No exercises in this module_

=== Links:

* https://landscape.cncf.io/
* https://csrc.nist.gov/publications/detail/sp/800-145/final

=== Lab tasks:

* Get a public git provider
* Get a Java-compatible IDE (VS Code, Intellij Idea, gitpod, Eclipse ...)
* Get a docker id
* Recommended: Local Docker/Container environment (Docker for Windows/Mac, Rancher Desktop)


